name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "*/5 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: NTTUCSIE-111
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_forks: yes
          config_timezone: Asia/Taipei
          plugin_activity: yes
          plugin_activity_timestamps: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartlist
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 20
          plugin_habits_languages_threshold: 0%
          output_action: none
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: out
        run: |
          set +e
          git checkout metrics-renders
          git config --global user.email bradly093@gmail.com
          git config --global user.name bradly0cjw
          sudo mv /metrics_renders/* ./
          git add --all
          git commit -m "chore: push metrics"
          git push
